In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
cd drive/MyDrive/Assignments

[Errno 2] No such file or directory: 'drive/MyDrive/Assignments'
/content/drive/MyDrive/Assignments

In [7]:
ls

 assign1/                          'Assignment-2-Set 4-Q 3.ipynb'
'Assign_Hypothesis_test Q1.ipynb'   BuyerRatio.csv
'Assign_Hypothesis_test Q2.ipynb'   Costomer+OrderForm.csv
'Assign_Hypothesis_test Q3.ipynb'   Cutlets.csv
'Assignment-2-Set1-Q1 .ipynb'       LabTAT.csv
'Assignment-2-Set2-Q5 .ipynb'

In [4]:
import scipy.stats as stats
import statsmodels.api as sm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
centers = pd.read_csv('Costomer+OrderForm.csv')
centers.head(10)

  Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free
5   Error Free  Error Free  Error Free  Error Free
6   Error Free   Defective  Error Free  Error Free
7   Error Free  Error Free  Error Free  Error Free
8   Error Free  Error Free  Error Free  Error Free
9   Error Free  Error Free  Error Free  Error Free

In [9]:
centers.describe()

       Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [10]:
centers.isnull().sum()

Phillippines    0
Indonesia       0
Malta           0
India           0
dtype: int64

In [11]:
centers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB

Checking value counts in data

In [12]:
print(centers['Phillippines'].value_counts(),'\n',centers['Indonesia'].value_counts(),'\n',centers['Malta'].value_counts(),'\n',centers['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64
 Error Free    267
Defective      33
Name: Indonesia, dtype: int64
 Error Free    269
Defective      31
Name: Malta, dtype: int64
 Error Free    280
Defective      20
Name: India, dtype: int64

In [13]:
contingency_table = [[271,267,269,280],
                    [29,33,31,20]]
print(contingency_table)

[[271, 267, 269, 280], [29, 33, 31, 20]]

Calculating Expected Values for Observed data

In [14]:
stat, p, df, exp = stats.chi2_contingency(contingency_table)
print("Statistics = ",stat,"\n",'P_Value = ', p,'\n', 'degree of freedom =', df,'\n', 'Expected Values = ', exp)

Statistics =  3.858960685820355
 P_Value =  0.2771020991233135
 degree of freedom = 3
 Expected Values =  [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]

In [15]:
observed = np.array([271, 267, 269, 280, 29, 33, 31, 20])
expected = np.array([271.75, 271.75, 271.75, 271.75, 28.25, 28.25, 28.25, 28.25])

Compare Evidences with Hypothesis using t-statictic

In [16]:
test_statistic , p_value = stats.chisquare(observed, expected, ddof = df)
print("Test Statistic = ",test_statistic,'\n', 'p_value =',p_value)

Test Statistic =  3.858960685820355
 p_value = 0.4254298144535761

interpreting p-value

In [17]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('We reject Null Hypothesis there is a significance difference between TAT of reports of the laboratories')
else:
    print('We fail to reject Null hypothesis')

Significnace=0.050, p=0.425
We fail to reject Null hypothesis

# We fail to reject Null Hypothesis because of lack of evidence.